#!/usr/bin/python3

import PegPuzzle


puzzle = PegPuzzle.Puzzle()
solutions = puzzle.solve(parentHistory = [], all = False , output = True)
print("Solutions found:  " + str(len(solutions)))

exit(0)
